### ISSUE TITLE
Migrate issue tracker from Bitbucket to Github

### ISSUE THREAD

**Issue by ebramanti** [birkholz/wardrobe#1]
http://myoutfits.co/about/ lists the old Bitbucket issue tracker. Perhaps consolidating issues in this repo since My Outfits is open-source would be easier than managing two separate areas for issues.

Here is a tool that will help migrate issues (written in Python too!): https://github.com/jeffwidman/bitbucket-issue-migration

**Comment by birkholz** [comment]
Link changed. I'll manually move over issues that are still relevant.

**Comment by ebramanti** [comment]
@birkholz Thanks!
